name: Upload Python Package

on:
  push:
    branches:
      - "main"  # Runs this workflow only on the main branch

permissions:
  contents: write  # Necessary to allow writing changes (in case of version bump)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v4

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Uses Python 3.x, change if you need a specific version

    # Step 3: Upgrade pip and install necessary build tools
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build

    # Step 4: Build the package (creates the dist directory with the package files)
    - name: Build package
      run: python -m build

    # Step 5: Publish the package to PyPI
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.6.4  # This is the latest stable tag
      with:
        password: ${{ secrets.PYPI_API_KEY }}  # Your PyPI token stored in GitHub Secrets
        skip_existing: true  # This will skip files that already exist on PyPI