name: Upload Python Package

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build bump2version

    # Step 4: Bump the version
    - name: Bump version
      run: bump2version patch  # Can be 'patch', 'minor', or 'major'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required to commit the version bump

    # Step 5: Build the package
    - name: Build package
      run: python -m build

    # Step 6: Publish the package to PyPI
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        password: ${{ secrets.PYPI_API_KEY }}